#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';

// Parse arguments
const args = process.argv.slice(2);
const migrationName = args[0];

if (!migrationName) {
  console.error('Please provide a migration name.');
  console.error('Usage: npm run create-migration <name>');
  process.exit(1);
}

// Ensure directories exist
const mapperDir = path.resolve(process.cwd(), 'src/mapper');
const migrationsDir = path.join(mapperDir, 'migrations');
const schemasDir = path.join(mapperDir, 'schemas');

[mapperDir, migrationsDir, schemasDir].forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

// Generate timestamp: YYYYMMDDHHMMSS
const now = new Date();
const timestamp = now.toISOString().replace(/[-T:.]/g, '').substring(0, 14);
const fileName = `${timestamp}_${migrationName}.ts`;
const filePath = path.join(migrationsDir, fileName);

// Migration template
const template = `import { TableMigrator } from '../../../dist/index.js';

export async function up() {
  const migrator = new TableMigrator('${migrationName}');
  
  // Define columns
  migrator.addColumn('id').type('int').autoIncrement().isPrimary();
  migrator.addColumn('created_at').type('date').default('NOW()');
  
  // Execute changes
  await migrator.exec();
}

export async function down() {
  const migrator = new TableMigrator('${migrationName}');
  await migrator.drop().exec();
}
`;

fs.writeFileSync(filePath, template);

console.log(`Created migration: ${filePath}`);

// Create/Update schema definition placeholder if it doesn't exist
// The actual schema file will be updated by running the migration
const schemaFilePath = path.join(schemasDir, `${migrationName}.ts`);
if (!fs.existsSync(schemaFilePath)) {
  const schemaTemplate = `// This file is auto-generated by the migration system
export const ${migrationName} = {
    fields: [],
    collection: '${migrationName}'
};
`;
  fs.writeFileSync(schemaFilePath, schemaTemplate);
  console.log(`Created schema placeholder: ${schemaFilePath}`);
}

// Update registry (src/mapper/migrations/index.ts)
const indexFilePath = path.join(migrationsDir, 'index.ts');
let imports = '';
let exports = 'export const migrations = [\n';

// Read all migration files
const files = fs.readdirSync(migrationsDir)
  .filter((f: string) => f.endsWith('.ts') && f !== 'index.ts')
  .sort(); // Sort by timestamp

files.forEach((f: string) => {
  const name = f.replace('.ts', '');
  const varName = `mig_${name.replace(/[^a-zA-Z0-9]/g, '_')}`;
  imports += `import * as ${varName} from './${name}.js';\n`;
  exports += `  { name: '${name}', ...${varName} },\n`;
});

exports += '];\n';

fs.writeFileSync(indexFilePath, `${imports}\n${exports}`);
console.log(`Updated migration registry: ${indexFilePath}`);

